# Generated by Django 2.0.7 on 2020-01-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chatbot',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='title',
            new_name='name',
        ),
    ]
