# Generated by Django 2.0.7 on 2020-01-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20200101_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='query',
            field=models.TextField(max_length=30),
        ),
    ]
