# Generated by Django 2.0.7 on 2020-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20200101_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='email',
            field=models.EmailField(default='someone@gmai.com', max_length=50),
        ),
    ]
