# Generated by Django 2.0.7 on 2020-01-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chat_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='email',
            field=models.EmailField(default='someone@gmail.com', max_length=50),
        ),
    ]
